### ISSUE TITLE
스프링 공식 문서 쓱 보기

### ISSUE THREAD

**Issue by muf** [muf/dev_posting#1]
> 그냥 쓱 가볍게 하나씩 보면서 가성비 있게 가자
> 궁금한건 몇개 정해서 시간내서 하나씩 공부
> 꼭 하고 싶은건 포함: 기본 주요 개념들 (ioc, aop 등) + 패턴 공부

## task
- [x] #6
  > https://spring.io/projects/spring-framework#support
- [x] #7
- [ ] Spring Reactor Core
- [ ] 현재 사용하는 (댓글 참고) 중요한 요소들 찾아서 공부
- [ ] 궁금한거 몇개만 정하고 별도 이슈로 진행, 이게 완료되면 그 시점에 다시 몇개 선정하고 이걸 반복 `천천히 여유두고 진행`

**Comment by muf** [comment]
- 일단 토비스프링으로 쓱 겉핥기를 하면서, 궁금한 부분 코드 확인 / 가이드 문서 체크 등으로 심도 있게 확인해보자 `코드로 확인하는게 제일 중요`
  - https://github.com/spring-projects
  - https://spring.io/projects
  - https://github.com/spring-projects/spring-framework
  - ...

**Comment by muf** [comment]
- [ ] spring 프레임워크 셋 전체 구경
  > https://spring.io/projects/spring-framework#support
